/** @deprecated Import from `@paid-tw/payment-ecpay` instead. */
export {
  createEcpayProvider,
  createEcpayEcpgProvider,
  computeCheckMacValue,
  verifyPaymentNotify,
  verifyEcpgPaymentNotify,
  ECPAY_NOTIFY_ACK,
  ECPG_NOTIFY_ACK,
  ECPAY_SANDBOX,
  ECPAY_SANDBOX_PORTAL,
  ECPAY_ORIGINS,
  ECPG_ORIGINS,
  type EcpayProvider,
  type EcpayEcpgProvider,
  type EcpayCheckoutForm,
  type EcpayRefundResult,
  type EcpayPaymentNotify,
  type EcpgPaymentNotify,
} from "@paid-tw/payment-ecpay";
