export type BankInfo = {
  code: string;
  fullName: string;
  shortName?: string;
};

const BANKS: BankInfo[] = [
  { code: "700", fullName: "中華郵政", shortName: "中華郵政" },
  { code: "104", fullName: "台北市第五信用合作社", shortName: "北五" },
  { code: "114", fullName: "基隆第一信用合作社", shortName: "基一" },
  { code: "115", fullName: "基隆市第二信用合作社", shortName: "基二" },
  { code: "119", fullName: "淡水第一信用合作社", shortName: "淡一" },
  { code: "120", fullName: "新北市淡水信用合作社", shortName: "淡信" },
  { code: "124", fullName: "宜蘭信用合作社", shortName: "宜信" },
  { code: "127", fullName: "桃園信用合作社", shortName: "桃信" },
  { code: "130", fullName: "新竹第一信用合作社", shortName: "竹一" },
  { code: "132", fullName: "新竹第三信用合作社", shortName: "竹三" },
  { code: "146", fullName: "台中市第二信用合作社", shortName: "中二" },
  { code: "158", fullName: "彰化第一信用合作社", shortName: "彰一" },
  { code: "161", fullName: "彰化第五信用合作社", shortName: "彰五" },
  { code: "162", fullName: "彰化第六信用合作社", shortName: "彰六" },
  { code: "163", fullName: "彰化第十信用合作社", shortName: "彰十" },
  { code: "165", fullName: "彰化縣鹿港信用合作社", shortName: "鹿信" },
  { code: "178", fullName: "嘉義市第三信用合作社", shortName: "嘉三" },
  { code: "188", fullName: "台南第三信用合作社", shortName: "南三" },
  { code: "204", fullName: "高雄市第三信用合作社", shortName: "高三" },
  { code: "215", fullName: "花蓮第一信用合作社", shortName: "花一" },
  { code: "216", fullName: "花蓮第二信用合作社", shortName: "花二" },
  { code: "222", fullName: "澎湖縣第一信用合作社", shortName: "澎一" },
  { code: "223", fullName: "澎湖第二信用合作社", shortName: "澎二" },
  { code: "224", fullName: "金門縣信用合作社", shortName: "金門" },
  { code: "004", fullName: "臺灣銀行", shortName: "臺銀" },
  { code: "005", fullName: "臺灣土地銀行", shortName: "土銀" },
  { code: "006", fullName: "合作金庫商業銀行", shortName: "合庫商銀" },
  { code: "007", fullName: "第一商業銀行", shortName: "一銀" },
  { code: "008", fullName: "華南商業銀行", shortName: "華銀" },
  { code: "009", fullName: "彰化商業銀行", shortName: "彰銀" },
  { code: "011", fullName: "上海商業儲蓄銀行", shortName: "上銀" },
  { code: "012", fullName: "台北富邦商業銀行", shortName: "北富銀" },
  { code: "013", fullName: "國泰世華商業銀行", shortName: "國世銀" },
  { code: "016", fullName: "高雄銀行", shortName: "高銀" },
  { code: "017", fullName: "兆豐國際商業銀行", shortName: "兆豐銀" },
  { code: "018", fullName: "全國農業金庫", shortName: "農業金庫" },
  { code: "020", fullName: "日商瑞穗銀行台北分行", shortName: "瑞穗銀行" },
  { code: "021", fullName: "花旗（台灣）商業銀行", shortName: "花旗台灣" },
  { code: "022", fullName: "美國銀行台北分行", shortName: "美銀台北" },
  { code: "023", fullName: "泰國盤谷銀行台北分行", shortName: "盤谷台北" },
  { code: "025", fullName: "菲律賓首都銀行台北分行", shortName: "首都台北" },
  { code: "029", fullName: "新加坡商大華銀行台北分行", shortName: "大華銀台北" },
  { code: "030", fullName: "美商道富銀行台北分行", shortName: "道富銀行" },
  { code: "037", fullName: "法商法國興業銀行台北分行", shortName: "法興台北" },
  { code: "039", fullName: "澳盛（台灣）商業銀行", shortName: "澳盛台灣" },
  { code: "048", fullName: "台灣工業銀行", shortName: "台灣工銀" },
  { code: "050", fullName: "臺灣中小企業銀行", shortName: "臺企" },
  { code: "052", fullName: "渣打國際商業銀行", shortName: "渣商銀" },
  { code: "053", fullName: "台中商業銀行", shortName: "台中銀" },
  { code: "054", fullName: "京城商業銀行", shortName: "京城銀行" },
  { code: "060", fullName: "兆豐票券金融股份有限公司", shortName: "兆豐票券" },
  { code: "061", fullName: "中華票券", shortName: "華票" },
  { code: "062", fullName: "國際票券", shortName: "國票" },
  { code: "066", fullName: "萬通票券金融股份有限公司", shortName: "萬票" },
  { code: "072", fullName: "德商德意志銀行台北分行", shortName: "德銀台北" },
  { code: "075", fullName: "香港商東亞銀行台北分行", shortName: "東亞銀行" },
  { code: "076", fullName: "美商摩根大通銀行台北分行", shortName: "摩根大通銀" },
  { code: "081", fullName: "匯豐（台灣）商業銀行", shortName: "匯豐台灣" },
  { code: "082", fullName: "法國巴黎銀行台北分行", shortName: "巴黎銀行" },
  { code: "085", fullName: "新加坡商新加坡華僑銀行台北分行", shortName: "新僑銀行" },
  { code: "086", fullName: "法商東方匯理銀行台北分行", shortName: "東方匯理" },
  { code: "092", fullName: "瑞士商瑞士銀行台北分行", shortName: "瑞士銀行" },
  { code: "093", fullName: "荷商安智銀行台北分行", shortName: "安智銀行" },
  { code: "098", fullName: "日商三菱東京日聯銀行台北分行", shortName: "三菱日聯" },
  { code: "101", fullName: "瑞興商業銀行", shortName: "瑞興銀行" },
  { code: "102", fullName: "華泰商業銀行", shortName: "華泰銀行" },
  { code: "103", fullName: "臺灣新光商業銀行", shortName: "新光銀行" },
  { code: "108", fullName: "陽信商業銀行", shortName: "陽信銀行" },
  { code: "118", fullName: "板信商業銀行", shortName: "板信銀行" },
  { code: "147", fullName: "三信商業銀行", shortName: "三信銀行" },
  { code: "321", fullName: "日商三井住友銀行台北分行", shortName: "三井住友" },
  { code: "372", fullName: "大慶票券金融股份有限公司", shortName: "大慶票券" },
  { code: "380", fullName: "大陸商中國銀行臺北分行", shortName: "中銀臺北" },
  { code: "381", fullName: "大陸商交通銀行臺北分行", shortName: "交銀臺北" },
  { code: "382", fullName: "大陸商中國建設銀行臺北分行", shortName: "建行臺北" },
  { code: "803", fullName: "聯邦商業銀行", shortName: "聯邦銀行" },
  { code: "805", fullName: "遠東國際商業銀行", shortName: "遠東銀行" },
  { code: "806", fullName: "元大商業銀行", shortName: "元大銀行" },
  { code: "807", fullName: "永豐商業銀行", shortName: "永豐銀行" },
  { code: "808", fullName: "玉山商業銀行", shortName: "玉山銀行" },
  { code: "809", fullName: "凱基商業銀行", shortName: "凱基銀行" },
  { code: "810", fullName: "星展（台灣）商業銀行", shortName: "星展台灣" },
  { code: "812", fullName: "台新國際商業銀行", shortName: "台新銀行" },
  { code: "814", fullName: "大眾商業銀行", shortName: "大眾銀行" },
  { code: "815", fullName: "日盛國際商業銀行", shortName: "日盛銀行" },
  { code: "816", fullName: "安泰商業銀行", shortName: "安泰銀行" },
  { code: "822", fullName: "中國信託商業銀行", shortName: "中信銀行" }
];

const BANK_MAP = new Map(BANKS.map((bank) => [bank.code, bank]));

export function getBankDisplay(code?: string) {
  if (!code) return undefined;
  const bank = BANK_MAP.get(code);
  if (!bank) return undefined;
  return `${bank.code} ${bank.fullName}`;
}
